### ISSUE TITLE
[Bug] expression visualization error

### ISSUE THREAD

**Issue by T0nyX1ang** [T0nyX1ang/42-Points-Game#6]
In a game, the following expressions are judged as equivalent:
* 9/(2-11/6)-12
* 9/(11/6-2)+12

But the visualization of the latter one is wrong.

Here are the exceptions:
```cmd
>>> from ftptsgame import FTPtsGame
>>> app = FTPtsGame()
>>> app.generate_problem([2,6,9,11,12])
>>> app.start()
>>> app.solve('9/(2-11/6)-12')
datetime.timedelta(seconds=17, microseconds=617000)
>>> app.solve('9/(11/6-2)+12')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\ftptsgame\__init__.py", line 129, in solve
    self.__validate_repeated(node)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\ftptsgame\__init__.py", line 99, in __validate_repeated
    class_id = self.__problem_class.equivalence_dict[node.unique_id()]
KeyError: '-[12]/[9]-[2]/[11][6]'
```

**Comment by T0nyX1ang** [comment]
Fixed in the last commit.
